/**
 * Canonical JANUS7 hook topic names used across runtime, services, and UI.
 *
 * @type {Readonly<Record<string, string>>}
 */
export const HOOKS = Object.freeze({
  ENGINE_READY:    'janus7.ready',
  STATE_LOADED:    'janus7.state.loaded',
  STATE_CHANGED:   'janus7.state.changed',
  STATE_REPLACED:  'janus7.state.replaced',
  STATE_SAVED:     'janus7.state.saved',
  CAMPAIGN_UPDATED:'janus7.campaign.updated',
  ENTITY_LINKED:   'janus7.entity.linked',
  ENTITY_IMPORTED: 'janus7.entity.imported',
  ROLL_COMPLETED:           'janus7.roll.completed',
  OPPOSED_TEST_FINISHED:    'janus7.roll.opposed.finished',
  ROLL_CRITICAL:            'janus7.roll.critical',
  ROLL_FUMBLE:              'janus7.roll.fumble',
  TOKEN_ATTRIBUTE_MODIFIED: 'janus7.token.attribute.modified',
  UI_THEME_CHANGED:         'janus7.ui.theme.changed',
  DSA_CALENDAR_UPDATED:     'janus7.dsa.calendar.updated',
  MOON_PHASE_CHANGED:       'janus7.moon.phase.changed',
  SCHIP_USED:               'janus7.fate.schip.used',
  DATE_CHANGED: 'janus7.date.changed',
  SCORE_CHANGED: 'janus7.scoring.changed',
  LESSON_STARTED:            'janus7.lesson.started',
  LESSON_DOCUMENTS_READY:    'janus7.lesson.documents.ready',
  LEARNING_PROGRESS_APPLIED: 'janus7.learning.progress',
  EFFECTS_APPLIED:           'janus7.effects.applied',
  EXAM_RESULT_RECORDED: 'janus7.exam.result.recorded',
  GROUP_EXAM_COMPLETED: 'janus7.exam.group.completed',
  QUEST_SYSTEM_READY:    'janus7.quest.system.ready',
  QUEST_STARTED:         'janus7.quest.started',
  QUEST_NODE_CHANGED:    'janus7.quest.node.changed',
  QUEST_COMPLETED:       'janus7.quest.completed',
  TRIMESTER_COMPLETED:   'janus7.trimester.completed',
  EVENT_SHOWN:           'janus7.event.shown',
  EVENT_MESSAGE:         'janus7.event.message',
  EVENT_OPTION_SELECTED: 'janus7.event.option.selected',
  RELATION_CHANGED:   'janus7.social.relation.changed',
  STORY_HOOK_CHANGED: 'janus7.social.story_hook.changed',
  CIRCLE_ASSIGNED:    'janus7.social.circle.assigned',
  FATE_EVENT_TRACKED: 'janus7.fate.tracked',
  LOCATION_CHANGED:   'janus7.location.changed',
  ATMOSPHERE_CHANGED: 'janus7.atmosphere.changed',
  KI_EXPORTED:        'janus7.ki.exported',
  KI_IMPORT_APPLIED:  'janus7.ki.import.applied',
  PROGRESSION_TICK:       'janus7.progression.tick',
  RESOURCE_CHANGED:       'janus7.progression.resource.changed',
  MILESTONE_RESOLVED:     'janus7.progression.milestone.resolved',
  COLLECTION_UPDATED:     'janus7.progression.collection.updated',
  SOCIAL_LINK_CHANGED:    'janus7.progression.social.changed',
  ACADEMY_DATA_RELOADED:  'janus7.academy.data.reloaded',
  DSA5_INDEX_UPDATED:     'janus7.dsa5.index.updated',
  MECHANIC_GATE_OPENED:   'janus7.progression.mechanic_gate.opened',
  EVENT_POOL_ACTIVATED:   'janus7.progression.event_pool.activated',
  LIBRARY_INDEX_PROGRESS: 'janusLibraryProgress',
  MISHAP_GENERATED:        'janus7.mishap.generated',
});

/**
 * Legacy hook aliases mapped by canonical topic for backwards compatibility.
 *
 * @type {Readonly<Record<string, readonly string[]>>}
 */
export const HOOK_ALIASES = Object.freeze({
  ['janus7.ready']:                   ['janus7Ready'],
  ['janus7.state.loaded']:            ['janus7StateLoaded'],
  ['janus7.state.changed']:           ['janus7StateChanged'],
  ['janus7.state.replaced']:          ['janus7StateReplaced'],
  ['janus7.state.saved']:             ['janus7StateSaved'],
  ['janus7.campaign.updated']:        ['janusCampaignStateUpdated'],
  ['janus7.entity.linked']:           ['janus7EntityLinked'],
  ['janus7.entity.imported']:         ['janus7EntityImported'],
  ['janus7.roll.completed']:          ['janus7RollCompleted'],
  ['janus7.roll.opposed.finished']:   ['janus7OpposedTestFinished'],
  ['janus7.roll.critical']:           ['janus7CriticalSuccess'],
  ['janus7.roll.fumble']:             ['janus7FumbleConditionApplied'],
  ['janus7.token.attribute.modified']:['janus7TokenAttributeModified'],
  ['janus7.dsa.calendar.updated']:    ['janus7DSACalendarUpdated'],
  ['janus7.moon.phase.changed']:      ['janus7MoonPhaseChanged'],
  ['janus7.fate.schip.used']:         ['janus7SchipUsed'],
  ['janus7.date.changed']:            ['janus7DateChanged'],
  ['janus7.scoring.changed']:         ['janus7ScoreChanged'],
  ['janus7.lesson.started']:          ['janus7LessonStarted'],
  ['janus7.lesson.documents.ready']:  ['janus7LessonDocumentsReady'],
  ['janus7.learning.progress']:       ['janus7LearningProgressApplied'],
  ['janus7.effects.applied']:         ['janus7EffectsApplied'],
  ['janus7.exam.result.recorded']:    ['janus7ExamResultRecorded'],
  ['janus7.exam.group.completed']:    ['janus7GroupExamCompleted'],
  ['janus7.quest.system.ready']:      ['janus7QuestSystemReady'],
  ['janus7.quest.started']:           ['janus7QuestStarted'],
  ['janus7.quest.node.changed']:      ['janus7QuestNodeChanged'],
  ['janus7.quest.completed']:         ['janus7QuestCompleted'],
  ['janus7.event.shown']:             ['janus7EventShown'],
  ['janus7.event.message']:           ['janus7EventMessage'],
  ['janus7.event.option.selected']:   ['janus7EventOptionSelected'],
  ['janus7.social.relation.changed']: ['janus7RelationChanged'],
  ['janus7.social.story_hook.changed']: ['janus7StoryHookChanged'],
  ['janus7.social.circle.assigned']:  ['janus7CircleAssigned'],
  ['janus7.fate.tracked']:            ['janus7FateEventTracked'],
  ['janus7.location.changed']:        ['janus7LocationChanged'],
  ['janus7.atmosphere.changed']:      ['janus7AtmosphereChanged'],
  ['janus7.ki.exported']:             ['janus7KiExported'],
  ['janus7.ki.import.applied']:       ['janus7KiImportApplied'],
  ['janus7.progression.tick']:              ['janus7ProgressionTick'],
  ['janus7.progression.resource.changed']:  ['janus7ResourceChanged'],
  ['janus7.progression.milestone.resolved']:['janus7MilestoneResolved'],
  ['janus7.progression.collection.updated']:['janus7CollectionUpdated'],
  ['janus7.progression.social.changed']:    ['janus7SocialLinkChanged'],
  ['janus7.academy.data.reloaded']:                ['janus7AcademyDataReloaded'],
  ['janus7.dsa5.index.updated']:                   ['janus7Dsa5IndexUpdated'],
  ['janus7.progression.mechanic_gate.opened']:     ['janus7MechanicGateOpened'],
  ['janus7.progression.event_pool.activated']:     ['janus7EventPoolActivated'],
});
